### ISSUE TITLE
[FEAT] 홈화면 개선 작업

### ISSUE THREAD

**Issue by hyuns66** [hyuns66/Pixionary#12]
# Description
새로운 기능추가를 위한 홈화면 마이그레이션
검색 카테고리 기능 추가를 위해 각 검색 페이지를 second page로 나누고 home화면을 통해 각 검색 페이지로 연결  

# TODO
- [x] 이미지 분석 process 홈화면에 표시 (dialog -> home activity)
- [x] Switch 버튼으로 검색 기능 전환
- [x] 홈화면 디자인 및 시작 액티비티로 적용

  
# ETC
기타 사항을 입력해주세요
