### ISSUE TITLE
[FEAT] Feature Store 구축

### ISSUE THREAD

**Issue by hyuns66** [hyuns66/Pixionary#2]
# Description

갤러리 내 이미지들 벡터화 하여 data base에 저장
벡터화된 feature들을 불러와 이미지 검색 추론시 활용 및 정렬 후 결과 표시
key - value 형식으로 저장해야함 (imagePath - feature_vector)
따라서 key - value 형식이며 불러오기 속도가 빠른 경량 데이터베이스가 적합.
고려사항 : 유저마다 이미지를 얼마나 보유하고있는지 모르기 때문에 저장해야할 데이터가 많을 수 있음. 메모리 용량 고려 필요할듯, FloatArray를 저장해야하는데 직렬화해서 저장하면 읽는데 속도가 느림. 개선방안 필요.

---

https://github.com/AlexeyZatsepin/Android-ORM-benchmark
위 연구결과 보면 NoSQL 기반 Realm이 SQLite 데이터 저장소 기반인 Room 보다 읽기속도가 압도적으로 빠름.
또한 NoSQL이 key - value 형식인점을 감안하여 Realm 채택하지 않을 이유가 없어보임.

---

혼자 고민만하면 답안나온다 직접 발로뛰어서 구현해보고 비교해보고 블로그에 벤치마킹 하자
- SharedPreferences
- PrefDatastore
- Realm
- ObjectBox 
- Room
- File  

요구사항 : 3만개의 Float형 데이터를 빨리 읽어와서 순서대로 정렬해야함. 쓰기속도는 비교적 우선순위가 낮음. (초기화 단계에서 한 번만 수행되며 변하지 않는 정적 데이터 특성)

# TODO
- [x] Shared Preferences 로 구현 (난이도 쉽고 빠르게 구현 가능)
  - [x] FloarArray 직렬화해서 저장하는 방식으로 일단 구현은 하나 성능이 좋지않음. 
- [x] Data Store로 마이그레이션
- [x] ~~FloatArray를 효율적으로 저장하는 방법 있는지 확인 필요~~
- [x] 디비 벤치마킹
  - [x] SharedPreferences
  - [x] prefDatastore
  - [x] Realm
  - [x] ObjectBox
  - [x] Room
  - [x] File     

  
# 참고 링크
[외국인 벤치마킹 블로그 Realm, Room, ObjectBox](https://notes.devlabs.bg/realm-objectbox-or-room-which-one-is-for-you-3a552234fd6e)
