### ISSUE TITLE
[FEAT] 병렬 연산 적용

### ISSUE THREAD

**Issue by hyuns66** [hyuns66/Pixionary#4]
# Description
단일 스레드 사용했을 때 추론에 너무 많은시간 소요
다중 스레드 사용하여 병렬적으로 추론, 소요시간 단축 필수적임
  

# TODO
- [x] ViewModelScope에서 다중 스레드 연산 구현
- [x] 스레드 coroutine간 연산 결과 공유 및 하나의 스레드에서 결과 취합 -> 액티비티에 전달
- [x] cpu 갯수에 따라 스레드 수 조절, 성능 개선여부 벤치마킹
    - [x] cpu 스케줄러에 따라 할당받으므로 해당작업을 독점적으로 진행하는것이 불가능. 몇개의 코어를 사용할지 실험적인 방법으로 증명 필요
    - [x] 코틀린의 경우 작업의 무거움과 코루틴의 숫자에 따라 코루틴이 더 빠르거나 느릴 수 있으므로 코루틴 또한 비교해봐야함

**고려사항**
thread vs coroutine?
경량 스레드의 오버헤드: 코루틴은 스레드보다 경량으로 설계되었지만, 특정 상황에서는 스레드에 비해 성능이 떨어질 수 있습니다. 예를 들어, 많은 코루틴이 동시에 실행되고 서로 많이 대기하는 경우, 스레드에 비해 오히려 성능이 떨어질 수 있습니다.
스레드의 본질 : 병렬성 -> 여러개의 코어를 활용해서 물리적 병렬연산 제공
코루틴의 본질 : 병행성 -> 싱글코어에서 time-sharing을 통해 여러 루틴이 동시에 실행되는거처럼 보이게함 (논리적 병렬성)

해당 이슈의 경우 concurrency가 중요한것이 아님. 멀티코어를 활용하여 연산을 빠르게 돌리는것이 목적이므로 멀티스레딩을 활용해야할것. 
그러나 문제점은 스레드를 너무 많이 할당해서 단일코어 멀티스레딩 문제가 생기는것 -> 컨텍스트 스위칭 비용 때문에 오히려 연산속도가 늦어지는 문제 발생

하드웨어의 모든 코어를 활용했을 때 cpu사용량 가장 높고 속도도 가장 빨랐지만, 발열문제 발생. -> 에너지 사용량, 발열량 추가비교해서 적절한 타협점 찾아야 함.

 reference : https://stackoverflow.com/questions/30119604/how-to-get-the-number-of-cores-of-an-android-device
# ETC
Single Coroutine
![image](https://github.com/user-attachments/assets/a0c51865-98f8-408d-aec5-7e4a5a79ec26)

Multi Coroutine - Dispatcher.Default  -  하드웨어 코어 수 만큼의 스레드풀
![image](https://github.com/user-attachments/assets/fb5070b6-16b8-4bf2-bb81-6cff2221aa5c)

Multi Coroutine - CustomThreadPool(4)  - 하드웨어 코어수의 절반
![image](https://github.com/user-attachments/assets/08eec99f-d194-482c-b50b-14420f3071ce)
