### ISSUE TITLE
[Refactoring] 하드웨어 추론 가속화

### ISSUE THREAD

**Issue by hyuns66** [hyuns66/Pixionary#5]
# Description
현재 추론시간이 너무오래걸림 다수이미지의 경우 더 심해지는 단점 존재
onDevice AI 추론 가속화 기법 시도해볼 필요 있음
  

# TODO
- [ ] Pruning
- [ ] Model Compression
- [ ] Model Quantization
- [ ] Weight Quantization
- [ ] Memory Access Reduction
- [ ] Loop Overhead Reduction
- [ ] TensorRT 와 같은 추론가속화 라이브러리 적용
- [ ] Increase BatchSize
- [ ] 하드웨어 가속화?

reference : https://onnxruntime.ai/docs/execution-providers/QNN-ExecutionProvider.html

# ETC
기타 사항을 입력해주세요
