### ISSUE TITLE
[FEAT] 백그라운드 스레드 적용 및 상시 동기화

### ISSUE THREAD

**Issue by hyuns66** [hyuns66/Pixionary#8]
# Description
이미지 feature store 초기화 과정에서 많은 시간 소요 예상
따라서 백그라운드에서 초기화 과정이 안정적으로 동작하도록 환경구축

# TODO
- [x] background Service 구현
- [ ] 중간에 비정상 종료되었을 때 진행프로세스 트래킹 및 복구
- [ ] BroadCastReceiver 활용하여 사진 촬영시마다 앱에 접속하지 않아도 자동 동기화 기능 구현
- [ ] 삭제한 사진에 해당하는 데이터 동기화

  
# ETC
기타 사항을 입력해주세요
