### ISSUE TITLE
[BUG] Native Memory Leak

### ISSUE THREAD

**Issue by hyuns66** [hyuns66/Pixionary#9]
# Description
모델 추론할 때 Native 영역 메모리 사용량이 계속해서 올라가고 줄어들지 않는현상 발생

# TODO
- [x] 메모리 누수 원인추론 및 제거
- [x] onnxRuntime에서 사용하는 Tensor 오브젝트가 메모리를 계속 먹고있음을 확인
레퍼런스 : https://github.com/microsoft/onnxruntime/issues/12895
https://github.com/microsoft/onnxruntime/issues/14641
- [x] file I/O 를 수행한 Stream은 반드시 close()를 명시적으로 해주어야함
> Streams have a BaseStream.close()method and implement AutoCloseable](https://docs.oracle.com/javase/8/docs/api/java/lang/AutoCloseable.html), but nearly all stream instances do not actually need to be closed after use. Generally, only streams whose source is an IO channel (such as those returned by [Files.lines(Path, Charset)](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#lines-java.nio.file.Path-java.nio.charset.Charset-)) will require closing. Most streams are backed by collections, arrays, or generating functions, which require no special resource management. (If a stream does require closing, it can be declared as a resource in a try-with-resources statement.)

레퍼런스 : https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html
https://stackoverflow.com/questions/34072035/why-is-files-lines-and-similar-streams-not-automatically-closed

  
# ETC
수정 전
vision
![image](https://github.com/user-attachments/assets/56152238-37aa-4f99-bba4-cd4455f0e277)
text
![image](https://github.com/user-attachments/assets/d32bcd77-a862-428d-9813-91065afb23d1)

수정 후
vision
![image](https://github.com/user-attachments/assets/47c410e5-db6b-4cc5-90bb-e1a6d3defbfd)
text
![image](https://github.com/user-attachments/assets/ada86164-200d-4f15-b7e9-f9e740ae4b3d)
